apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirage-frontend
  namespace: mirage
  labels:
    app: mirage-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mirage-frontend
  template:
    metadata:
      labels:
        app: mirage-frontend
    spec:
      containers:
      - name: mirage-frontend
        image: registry.digitalocean.com/mirage/mirage-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BACKEND_URL
          value: "http://mirage-backend:3000"
        envFrom:
        - secretRef:
            name: frontend-env

